name: dart_sentiment
description: A sentiment analyzer tool for dart apps.
version: 0.1.0
homepage: https://github.com/shane-lab/dart-sentiment/
author: Shane <info@shanelab.nl>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  build_runner: any
  test: any
  benchmark_harness: any
