name: dart_sentiment
description: A sentiment analyzer tool for dart apps.
# version: 1.0.0
homepage: https://ghg.shanelab.nl/
author: Shane <info@shanelab.nl>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  node_interop: any

dev_dependencies:
  build_runner: any
  test: any
  benchmark_harness: any
