name: dart_sentiment
description: A sentiment analyzer tool for dart apps.
# version: 1.0.0
homepage: https://ghg.shanelab.nl/
author: Shane <info@shanelab.nl>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  vue: ^0.4.0
  aspen_assets: any
  node_interop: any
  dryice: any
  http: any
  json_annotation: any
  tuple: any
  rxdart: any
  event_bus: ^1.0.1
  uuid: any

dev_dependencies:
  build_runner: any
  build_web_compilers: ^0.4.0
  aspen: any
  json_serializable: any
  test: any
